config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    post "/users", to: "users#create"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :products, only: :show
    resource :cart, except: %i(new edit) do
      get "/total", to: "carts#total"
    end
    resources :orders, only: %i(index create)

    namespace :admin do
      root "orders#index"
      resources :orders, only: %i(index show update)
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :handle_param_quantity, :load_product, only: :create
  before_action :load_cart_products, :verify_cart, only: :index

  def index; end

  def create
    current_qtt = quantity_in_cart @product.id
    new_qtt = current_qtt + @quantity
    if new_qtt > @product.quantity
      flash.now[:warning] = t ".insufficient"
    else
      update_cart @product.id, new_qtt
      flash.now[:success] = t ".success"
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def handle_param_quantity
    @quantity = params.dig(:cart, :quantity)&.to_i
    return if @quantity.positive?

    solve_invalid_req t(".invalid_qtt")
  end

  def load_product
    product_id = params.dig(:cart, :product_id)
    @product = Product.find_by id: product_id
    return if @product

    solve_invalid_req t("products.not_found")
  end

  def load_cart_products
    @cart_product_ids = cart_items.keys.map(&:to_i)
    @products = Product.where(id: @cart_product_ids)
  end

  def verify_cart
    unknown_cart_items = @cart_product_ids - @products.map(&:id)
    unknown_cart_items.each{|id| update_cart id, 0}

    @quantity = cart_items.values.map(&:to_i)
  end

  def solve_invalid_req message
    flash[:danger] = message
    redirect_to root_url
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_cart_products, :verify_cart, only: :show
  before_action :handle_param_quantity, :load_product, only: %i(create update)

  def show; end

  def create
    current_qtt = quantity_in_cart @product.id
    new_qtt = current_qtt + @quantity
    if new_qtt > @product.quantity
      flash.now[:warning] = t ".insufficient"
    else
      update_cart @product.id, new_qtt
      flash.now[:success] = t ".success"
    end

    respond_to do |format|
      format.js
    end
  end

  def update
    flash.now[:warning] = t ".insufficient" if @quantity > @product.quantity
    @new_qtt = [@quantity, @product.quantity].min
    update_cart @product.id, @new_qtt

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @product_id = params[:pid]
    if @product_id.nil?
      empty_cart
      flash[:success] = t ".empty_cart"
      return redirect_to root_url
    else
      update_cart @product_id, 0
    end

    respond_to do |format|
      format.js
    end
  end

  def total
    @total = Product.where(id: params[:product_ids])
                    .map{|p| p.final_price(quantity_in_cart(p.id))}
                    .sum

    respond_to do |format|
      format.js
    end
  end

  private

  def handle_param_quantity
    @quantity = params.dig(:cart, :quantity)&.to_i
    return if @quantity.positive?

    solve_invalid_req t(".invalid_qtt")
  end

  def load_product
    product_id = params.dig(:cart, :product_id)
    @product = Product.find_by id: product_id
    return if @product

    solve_invalid_req t("products.not_found")
  end

  def load_cart_products
    @cart_product_ids = cart_items.keys.map(&:to_i)
    @products = Product.where(id: @cart_product_ids)
  end

  def verify_cart
    unknown_cart_items = @cart_product_ids - @products.map(&:id)
    unknown_cart_items.each{|id| update_cart id, 0}

    @quantity = cart_items.values.map(&:to_i)
  end

  def solve_invalid_req message
    flash[:danger] = message
    redirect_to root_url
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  CART_KEY = :cart

  def init_cart
    set_cookie(CART_KEY, {}) unless cookies[CART_KEY]
  end

  def cart_items
    JSON.parse cookies[CART_KEY]
  end

  def quantity_in_cart product_id
    cart_items[product_id.to_s]&.to_i || 0
  end

  def update_cart product_id, new_quantity
    cart = cart_items
    if new_quantity.positive?
      cart[product_id.to_s] = new_quantity
    else
      cart.delete(product_id.to_s)
    end
    set_cookie CART_KEY, cart
  end

  def empty_cart product_ids = nil
    if product_ids.is_a? Array
      product_ids.each{|id| update_cart id, 0}
    else
      set_cookie CART_KEY, {}
    end
  end

  private

  def set_cookie key, value
    cookies[key] = {
      value: value.to_json,
      expires: 3.months.from_now,
      httponly: true
    }
  end
end

app/views/carts/_cart.html.erb
<div class="row m-btm-30">
  <div class="col-md-1 text-center">
    <input id="all-check" type="checkbox" class="checkbox m-auto">
  </div>
  <div class="col-md-4 text-capitalize text-important-bg"><%= t ".product_name" %></div>
  <div class="col-md-2 text-right text-important-bg"><%= t ".product_price" %></div>
  <div class="col-md-2 text-center text-important-bg"><%= t ".quantity" %></div>
  <div class="col-md-2 text-right text-important-bg"><%= t ".total" %></div>
  <div class="col-md-1">
    <%= link_to(cart_path, method: :delete, remote: true,
                data: { confirm: t(".del_all") }, class: "color-black") do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </div>
</div>

<% @products.each_with_index do |prod, idx| %>
  <div id="cart_item_<%= prod.id %>" class="row cart_items">
    <div class="col-md-1">
      <input type="checkbox" class="checkbox m-auto"
             name="prod-selector" value="<%= prod.id %>"
      >
    </div>

    <div class="col-md-4">
      <img src='<%= prod.image %>' alt='<%= prod.name %>'>
      <%= link_to prod.name, product_path(id: prod.slug) %>
    </div>

    <div class="col-md-2 text-right text-important">
      <%= number_to_currency prod.price %>
    </div>

    <div class="col-md-2">
      <div class="input_quantity_group m-0">
        <button pid="<%= prod.id %>" class="quantity_btn btn-qtt_decr" type="button">
          <span class="glyphicon glyphicon-minus"></span>
        </button>

        <input type="text" class="quantity_input text-center full-width"
               value="<%= @quantity[idx] %>" id="input-qtt-<%= prod.id %>"
        >

        <button pid="<%= prod.id %>" class="quantity_btn btn-qtt_incr" type="button">
          <span class="glyphicon glyphicon-plus"></span>
        </button>
      </div>
    </div>

    <div class="col-md-2 color-red text-important text-right"
         id="total-<%= prod.id %>"
    >
      <%= number_to_currency @quantity[idx] * prod.price %>
    </div>

    <div class="col-md-1">
      <%= link_to (cart_path(pid: prod.id)), method: :delete, remote: true,
                  data: { confirm: t(".del"), pid: prod.id }, class: "color-black del-product" do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </div>
  </div>
<% end %>

<%= render "cart_update_js" %>

app/views/carts/_cart_update_js.html.erb
<script type="text/javascript">
    function getSelectedProduct() {
        return $('input[name="prod-selector"]:checked').map(function () {
            return $(this).val();
        }).get();
    }

    function getTotalPrice() {
        const selectedProducts = getSelectedProduct();
        $.get(`<%= total_cart_path %>`, {
            product_ids: selectedProducts
        }).done(() => {
            $('#submit-order-btn').attr('disabled', selectedProducts.length === 0);
            $('#selected_amount').text(selectedProducts.length);
        });
    }

    $(document).ready(() => {
        $.ajaxSetup({
            headers: {"X-CSRF-Token": $("meta[name='csrf-token']").attr("content")},
        });

        // function to submit new quantity
        const update_quantity = (pid, step) => {
            let qtt = parseInt($(`#input-qtt-${pid}`).val());
            qtt += step;
            let data = {
                cart: {
                    product_id: pid,
                    quantity: qtt,
                }
            }
            if (qtt > 0) {
                $.ajax({
                    url: `<%= cart_path %>`,
                    type: 'PUT',
                    data
                }).done(getTotalPrice);
            }
        };

        $('a.del-product[data-remote]').each(function () {
            $(this).bind("ajax:success", function () {
                const pid = $(this).data('pid');
                $(`#cart_item_${pid}`).remove();
                getTotalPrice();
            });
        });

        const allCheckCB = $('#all-check');
        allCheckCB.click(() => {
            let isTrue = $('#all-check').prop("checked");
            $('input[name="prod-selector"]').prop("checked", isTrue);
            getTotalPrice();
        });

        $('input[name="prod-selector"][type="checkbox"]').bind('click', () => {
            allCheckCB.prop("checked", false);
            getTotalPrice();
        });

        const qtt_input = $('input.quantity_input[type="text"]');
        // ensure that the quantity input is a number
        qtt_input.keypress(event => {
            if (event.key.replace(/[^\d]/g, '') === '')
                event.preventDefault();
        });

        qtt_input.each(function () {
            // memorize the pre value
            $(this).on('focus', () => {
                $(this).data('oldVal', $(this).val());
            });
            $(this).on('blur', () => {
                let newValue = parseInt($(this).val());
                $(this).val(isNaN(newValue) ? 1 : Math.max(1, newValue));

                // if the value is changed, update the total
                let oldValue = parseInt($(this).data('oldVal'));
                if (oldValue !== newValue) {
                    const pid = $(this).attr('id').replace('input-qtt-', '')
                    update_quantity(pid, 0);
                }
            });
        });

        $('button.btn-qtt_decr').each(function () {
            $(this).on('click', () => {
                const pid = $(this).attr('pid');
                update_quantity(pid, -1);
            });
        });

        $('button.btn-qtt_incr').each(function () {
            $(this).on('click', () => {
                const pid = $(this).attr('pid');
                update_quantity(pid, 1);
            });
        });
    });
</script>

app/views/carts/_order_form.html.erb
<form id="order-form" class="form-horizontal">
  <div class="form-group">
    <label class="control-label col-sm-4"><%= t ".receiver" %></label>
    <div class="col-sm-8">
      <input type="text" class="form-control" name="receiver_name" required>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-4"><%= t ".phone" %></label>
    <div class="col-sm-8">
      <input type="text" class="form-control" name="phone" required>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-4"><%= t ".address" %></label>
    <div class="col-sm-8">
      <input type="text" class="form-control" name="deliver_address" required>
    </div>
  </div>
  <div>
    <div class="order_total">
      <div class="text-important text-right min-width-70"><%= t ".total" %></div>
      <div id="order_price" class="text-important-bg color-red">
        <%= number_to_currency(0) %>
      </div>
    </div>
    <button type="submit" class="btn btn-danger btn-block"
            id="submit-order-btn" disabled>
      <%= t ".buy" %>
      (<span id="selected_amount">0</span>)
    </button>
  </div>
</form>

<%= javascript_pack_tag "create_order" %>

app/views/carts/create.js.erb
$('#cart_amount').text('<%= cart_items.size %>');
<%= toastr_flash %>

app/views/carts/destroy.js.erb
$('#cart_amount').text('<%= cart_items.size %>');

app/views/carts/show.html.erb
<%= provide :title, t("layouts.header.cart") %>

<div class="row">
  <div class="col-md-9 pd-top-20">
    <%= render "cart" %>
  </div>

  <div class="col-md-3 pd-10">
    <%= render "order_form" %>
  </div>
</div>

app/views/carts/total.js.erb
$('#order_price').text('<%= number_to_currency @total %>');

app/views/carts/update.js.erb
$('#total-<%= @product.id %>').text('<%= number_to_currency @product.price * @new_qtt %>');
$('#input-qtt-<%= @product.id %>').val('<%= @new_qtt %>');
<%= toastr_flash %>