config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    post "/users", to: "users#create"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :products, only: :show
    resource :cart, except: %i(new edit) do
      get "/total", to: "carts#total"
    end
    resources :orders, only: %i(index create)

    namespace :admin do
      root "orders#index"
      resources :orders, only: %i(index show update)
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    <p><%= t "base_title" %></p>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to t(".en"), locale: :en %> |
        <%= link_to t(".vi"), locale: :vi %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="header__navbar">
      <div class="header__navbar-left">
        <%= link_to "SGM", root_path, class: "menu-logo" %>
        <div class="form-container">
          <form>
            <input
              type="text"
              class="form-input"
            />
            <input
              type="button"
              class="form-button"
              value="Search"
            />
          </form>
        </div>
      </div>
      <div class="header__navbar-right">
        <div class="header__navbar-right-menu">
        <% if logged_in? %>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.name %> <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <% if is_admin? %>
                <li><%= link_to "Admin", admin_root_path %></li>
              <% end %>
              <li><%= link_to t(".orders"), orders_path %></li>
              <li><%= link_to t(".settings"), "#" %></li>
              <li><%= link_to t(".sign_out"), signout_path, method: :delete %></li>
            </ul>
          </div>
        <% else %>
          <%= link_to t(".sign_up"), signup_path, class: "first-link" %>
          <%= link_to t(".sign_in"), signin_path %>
        <% end %>
        </div>
        <div class="cart">
          <%= link_to cart_path do %>
            <div class="cart-wrapper">
              <span class="glyphicon glyphicon-shopping-cart"></span>
              <span id="cart_amount" class="cart-wrapper-amount"><%= cart_items.size %></span>
            </div>

            <div>
              <%= t ".cart" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_header_admin.html.erb
<header>
  <div class="container">
    <div class="header__navbar">
      <div class="header__navbar-left">
        <%= link_to "SGM", root_path, class: "menu-logo" %>
      </div>
      <div class="header__navbar-right">
        <div class="header__navbar-right-menu">

        <% if logged_in? %>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.name %> <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <li><%= link_to t(".sign_out"), signout_path, method: :delete %></li>
            </ul>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= full_title yield(:title) %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header_admin" %>
    <main>
      <div class="container-fluid">
        <div class="row admin-container">
          <div class="col-md-2 admin_aside">
            <ul>
              <%= link_to admin_orders_path do %>
                <li><%= t ".orders" %></li>
              <% end %>

              <%= link_to "#" do %>
                <li><%= t ".users" %></li>
              <% end %>

              <%= link_to "#" do %>
                <li><%= t ".categories" %></li>
              <% end %>

              <%= link_to "#" do %>
                <li><%= t ".products" %></li>
              <% end %>
            </ul>
          </div>
          <div class="col-md-10">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>

  <script>
    <%= toastr_flash %>
  </script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= full_title yield(:title) %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
  <script>
    <%= toastr_flash %>
</script>
</html>